# Generated by Django 5.0.6 on 2024-05-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PIL1_2324_9_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='students',
        ),
    ]
